# API Server
web:
 build: ./
 container_name: motionbank-api
 ports:
  - 3030:3030
 volumes:
  - .:/app
 working_dir: /app
 links:
  - mongodb

# MongoDB
mongodb:
 image: douglaszuqueto/alpine-mongodb:3.2.7
 container_name: motionbank-api-mongodb
 ports:
  - 27017:27017
 volumes:
  - mongodb-data:/data/db
